### ISSUE TITLE
sigsegv when API server isn't running

### ISSUE THREAD

**Issue by craigmayhew** [dhappy/git-remote-ipfs#1]
Thank you for opening up the issues and for putting time into this project!

After installing go version 1.14 and using `make` to build the project, I get the following segfault when I try to push this repo to IPFS.

I'm unsure where to begin on debugging this, any pointers would be much appreciated.

This was on ubuntu 18.04 and I notice is an issue that has occurred before in the original shipyard research repo back in Feb 2019 https://github.com/ipfs-shipyard/git-remote-ipld/issues/23

```
$ git push ipfs:: master
< capabilities
> push
> fetch
>
< list for-push
> 0000000000000000000000000000000000000000 refs/heads/master
>
< push refs/heads/master:refs/heads/master
<
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7eed0e]

goroutine 1 [running]:
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Send(0xc00007e4b0, 0xeb9340, 0xc0000240d8, 0x50, 0xc412e0, 0xc00008e501)
        /home/user/go/pkg/mod/github.com/ipfs/go-ipfs-api@v0.0.1/requestbuilder.go:77 +0x3e
github.com/ipfs/go-ipfs-api.(*RequestBuilder).Exec(0xc00007e4b0, 0xeb9340, 0xc0000240d8, 0xb618c0, 0xc0002461f0, 0xbfdc01, 0xc000199788)
        /home/user/go/pkg/mod/github.com/ipfs/go-ipfs-api@v0.0.1/requestbuilder.go:86 +0x43
github.com/ipfs/go-ipfs-api.(*Shell).Add(0x0, 0x7f2c018643b0, 0xc0002461b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x35, 0x0)
        /home/user/go/pkg/mod/github.com/ipfs/go-ipfs-api@v0.0.1/add.go:58 +0x2d9
github.com/dhappy/git-remote-ipfs/core.(*Push).doWork(0xc0001248c0, 0xc0001501c0, 0x0, 0x0, 0x0, 0x0)
        /mnt/c/Users/day2day/Documents/GitHub/git-remote-ipfs/core/push.go:118 +0xccf
github.com/dhappy/git-remote-ipfs/core.(*Push).PushHash(0xc0001248c0, 0xc000029200, 0x28, 0xc0001501c0, 0x28, 0x0, 0x0, 0xc000074138)
        /mnt/c/Users/day2day/Documents/GitHub/git-remote-ipfs/core/push.go:61 +0x6f
main.(*IPFSHandler).Push(0xc000031c00, 0xc0001501c0, 0xc000029055, 0x11, 0xc000029067, 0x11, 0x2, 0xc000024640, 0x2, 0x0)
        /mnt/c/Users/day2day/Documents/GitHub/git-remote-ipfs/cmd/git-remote-ipfs/ipfs.go:165 +0x2ef
github.com/dhappy/git-remote-ipfs/core.(*Remote).push.func1(0xc00007e640, 0xc88cc6, 0x4, 0xc000199d28)
        /mnt/c/Users/day2day/Documents/GitHub/git-remote-ipfs/core/remote.go:100 +0x60
github.com/dhappy/git-remote-ipfs/core.(*Remote).ProcessCommands(0xc0001501c0, 0xc000031c00, 0xeaa420)
        /mnt/c/Users/day2day/Documents/GitHub/git-remote-ipfs/core/remote.go:158 +0x420
main.Main(0xc000020180, 0x3, 0x3, 0xeaa420, 0xc000010010, 0xeaa440, 0xc000010018, 0x0, 0x0)
        /mnt/c/Users/day2day/Documents/GitHub/git-remote-ipfs/cmd/git-remote-ipfs/main.go:58 +0x45d
main.main()
        /mnt/c/Users/day2day/Documents/GitHub/git-remote-ipfs/cmd/git-remote-ipfs/main.go:70 +0x79
error: failed to push some refs to 'ipfs::'
```

**Comment by craigmayhew** [comment]
FWIW Bumping go-ipfs-api to v0.0.3 in go.mod and recompiling doesn't seem to change the behaviour.

I also see the same behaviour when compiled under kali linux

**Comment by dysbulic** [comment]
@craigmayhew, I built and ran in both `go1.14` & `go1.14.2` in Ubuntu 18.04, and I've not been able to get it to segfault.

I simplified the install process a bit, could you give these a try and let me know if it's still crashing?

* `go get -v github.com/dhappy/git-remote-ipfs/cmd/git-remote-ipfs/...`
* `cp --no-dereference "$GOPATH/src/github.com/dhappy/git-remote-ipfs/cmd/git-remote-ipfs/git-remote-ipns" "$GOBIN"`

The second command assumes you have the `GOPATH` and `GOBIN` environment variables defined. All it is doing is copying a symlink so IPNS will work.

You'd also need to `rm /usr/lib/git-core/git-remote-ip*` and have `$GOBIN` in your `PATH`.

**Comment by craigmayhew** [comment]
That is much simpler to install :)

```sh
GOBIN=/home/user/go/bin/
GOPATH=/home/user/go/
go get -v github.com/dhappy/git-remote-ipfs/cmd/git-remote-ipfs/...
cp --no-dereference "$GOPATH/src/github.com/dhappy/git-remote-ipfs/cmd/git-remote-ipfs/git-remote-ipns" "$GOBIN"
sudo rm /usr/lib/git-core/git-remote-ip*
```

This also resulted in the same segfault. So I went back to the drawing board with my issue, on the presumption it was something I had done or skipped.

I realised that `ipfs daemon` had not been run 🤦 and so the segfault occurs when IPFS is not listening on localhost:5001 (as I was previously running IPFS daemon in a different environment).

**Comment by dysbulic** [comment]
That's a horrible looking error. There's got to be some way to check…

**Comment by craigmayhew** [comment]
Cheers for re-opening the issue.

I've looked at adding a more descriptive output message when this type of connection error occurs, however it's currently beyond my Go skills. I'll update this issue if I start working on a fix again as I need to put this down for now.

**Comment by dysbulic** [comment]
I rewrote everything in javascript and the new error when the server isn't running is more to the point.
